Parameters:
  githubRepoName:
    Type: String
    Default: pahud/aws-cdk-serverless-sample
    Description: The name github repo e.g. pahud/aws-cdk-serverless-sample
  stackName:
    Type: String
    Default: ""
    Description: Custom stack name for the CDK stack to deploy
  extraDeployArguments:
    Type: String
    Default: ""
    Description: extra arguments for cdk deploy

Mappings:
  AssetInfo:
    assets:
      S3VersionKey: "public/assets/||4a3609ad912843e581892f37ae9d6fb0fa1648b547693aaa562b0119452b8956.zip"
      ArtifactHash: "4a3609ad912843e581892f37ae9d6fb0fa1648b547693aaa562b0119452b8956"
  RegionMap:
    us-east-1:
      "bucket": "awscdkrun-us-east-1"
    us-east-2:
      "bucket": "awscdkrun-us-east-2"
    us-west-1:
      "bucket": "awscdkrun-us-west-1"
    us-west-2:
      "bucket": "awscdkrun-us-west-2"
    eu-central-1:
      "bucket": "awscdkrun-eu-central-1"
    eu-north-1:
      "bucket": "awscdkrun-eu-north-1"
    eu-west-1:
      "bucket": "awscdkrun-eu-west-1"
    eu-west-2:
      "bucket": "awscdkrun-eu-west-2"
    eu-west-3:
      "bucket": "awscdkrun-eu-west-3"
    ap-south-1:
      "bucket": "awscdkrun-ap-south-1"
    ap-southeast-1:
      "bucket": "awscdkrun-ap-southeast-1"
    ap-southeast-2:
      "bucket": "awscdkrun-ap-southeast-2"
    ap-northeast-1:
      "bucket": "awscdkrun-ap-northeast-1"
    ap-northeast-2:
      "bucket": "awscdkrun-ap-northeast-2"
    sa-east-1:
      "bucket": "awscdkrun-sa-east-1"
Resources:
  CDKRunDemoProjectCodeBuildProjectRole47F1E9C9:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join
          - ""
          - - "arn:"
            - !Ref "AWS::Partition"
            - ":iam::aws:policy/AdministratorAccess"
    Metadata:
      "aws:cdk:path": cdk-run-demo-stack/CDKRunDemoProject/CodeBuildProjectRole/Resource
  CDKRunDemoProjectCodeBuildProjectRoleDefaultPolicy49010D77:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Effect: Allow
            Resource:
              - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CDKRunDemoProject86EBB8A2}"
              - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CDKRunDemoProject86EBB8A2}:*"
          - Action:
              - "codebuild:CreateReportGroup"
              - "codebuild:CreateReport"
              - "codebuild:UpdateReport"
              - "codebuild:BatchPutTestCases"
              - "codebuild:BatchPutCodeCoverages"
            Effect: Allow
            Resource:
              - !Sub "arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group:${CDKRunDemoProject86EBB8A2}-*"
        Version: 2012-10-17
      PolicyName: CDKRunDemoProjectCodeBuildProjectRoleDefaultPolicy49010D77
      Roles:
        - !Ref CDKRunDemoProjectCodeBuildProjectRole47F1E9C9
    Metadata:
      "aws:cdk:path": >-
        cdk-run-demo-stack/CDKRunDemoProject/CodeBuildProjectRole/DefaultPolicy/Resource
  CDKRunDemoProject86EBB8A2:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: CUSTOM_STACK_NAME
            Type: PLAINTEXT
            Value: !Ref stackName
          - Name: EXTRA_DEPLOY_ARGS
            Type: PLAINTEXT
            Value: !Ref extraDeployArguments
        Image: "aws/codebuild/standard:4.0"
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt
        - CDKRunDemoProjectCodeBuildProjectRole47F1E9C9
        - Arn
      Source:
        BuildSpec: |-
          {
            "version": "0.2",
            "phases": {
              "install": {
                "commands": [
                  "yarn install"
                ]
              },
              "build": {
                "commands": [
                  "if [ -n $CUSTOM_STACK_NAME ]; then npx cdk diff -c stackName=\"${CUSTOM_STACK_NAME}\" ${EXTRA_DEPLOY_ARGS} || return 0; fi",
                  "if [ -n $CUSTOM_STACK_NAME ]; then npx cdk deploy -c stackName=\"${CUSTOM_STACK_NAME}\" --require-approval=never ${EXTRA_DEPLOY_ARGS}; fi",
                  "if [ -z $CUSTOM_STACK_NAME ]; then npx cdk diff ${EXTRA_DEPLOY_ARGS} || return 0; fi",
                  "if [ -z $CUSTOM_STACK_NAME ]; then npx cdk deploy --require-approval=never ${EXTRA_DEPLOY_ARGS}; fi"
                ]
              }
            }
          }
        Location: !Join
          - ""
          - - "https://github.com/"
            - !Select
              - 0
              - !Split
                - /
                - !Ref githubRepoName
            - /
            - !Select
              - 1
              - !Split
                - /
                - !Ref githubRepoName
            - .git
        ReportBuildStatus: true
        Type: GITHUB
      EncryptionKey: alias/aws/s3
    Metadata:
      "aws:cdk:path": cdk-run-demo-stack/CDKRunDemoProject/Project/Resource
  ? CDKRunDemoProjectStartBuildCDKRunDemoProjectStarterCustomResourcePolicy835B7D22
  : Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Action: "codebuild:StartBuild"
            Effect: Allow
            Resource: "*"
        Version: 2012-10-17
      PolicyName: >-
        CDKRunDemoProjectStartBuildCDKRunDemoProjectStarterCustomResourcePolicy835B7D22
      Roles:
        - !Ref AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      "aws:cdk:path": >-
        cdk-run-demo-stack/CDKRunDemoProject/StartBuildCDKRunDemoProject/Starter/CustomResourcePolicy/Resource
  CDKRunDemoProjectStartBuildCDKRunDemoProjectStarterA4953E00:
    Type: "Custom::AWS"
    Properties:
      ServiceToken: !GetAtt
        - AWS679f53fac002430cb0da5b7982bd22872D164C4C
        - Arn
      Create:
        service: CodeBuild
        action: startBuild
        parameters:
          projectName: !Ref CDKRunDemoProject86EBB8A2
        physicalResourceId:
          id: !Ref CDKRunDemoProject86EBB8A2
      Update:
        service: CodeBuild
        action: startBuild
        parameters:
          projectName: !Ref CDKRunDemoProject86EBB8A2
        physicalResourceId:
          id: !Ref CDKRunDemoProject86EBB8A2
      InstallLatestAwsSdk: true
    DependsOn:
      - >-
        CDKRunDemoProjectStartBuildCDKRunDemoProjectStarterCustomResourcePolicy835B7D22
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      "aws:cdk:path": >-
        cdk-run-demo-stack/CDKRunDemoProject/StartBuildCDKRunDemoProject/Starter/Resource/Default
  AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join
          - ""
          - - "arn:"
            - !Ref "AWS::Partition"
            - ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
    Metadata:
      "aws:cdk:path": >-
        cdk-run-demo-stack/AWS679f53fac002430cb0da5b7982bd2287/ServiceRole/Resource
  AWS679f53fac002430cb0da5b7982bd22872D164C4C:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !FindInMap [RegionMap, !Ref "AWS::Region", bucket]
        S3Key: !Join
          - ""
          - - !Select
              - 0
              - !Split
                - "||"
                - !FindInMap [AssetInfo, assets, S3VersionKey]
            - !Select
              - 1
              - !Split
                - "||"
                - !FindInMap [AssetInfo, assets, S3VersionKey]
      Handler: index.handler
      Role: !GetAtt
        - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
        - Arn
      Runtime: nodejs12.x
      Timeout: 120
    DependsOn:
      - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      "aws:cdk:path": cdk-run-demo-stack/AWS679f53fac002430cb0da5b7982bd2287/Resource
      "aws:asset:path": asset.4a3609ad912843e581892f37ae9d6fb0fa1648b547693aaa562b0119452b8956
      "aws:asset:property": Code
  CDKMetadata:
    Type: "AWS::CDK::Metadata"
    Properties:
      Modules: >-
        aws-cdk=1.74.0,@aws-cdk/assets=1.74.0,@aws-cdk/aws-applicationautoscaling=1.74.0,@aws-cdk/aws-autoscaling-common=1.74.0,@aws-cdk/aws-cloudwatch=1.74.0,@aws-cdk/aws-codebuild=1.74.0,@aws-cdk/aws-codeguruprofiler=1.74.0,@aws-cdk/aws-ec2=1.74.0,@aws-cdk/aws-ecr=1.74.0,@aws-cdk/aws-ecr-assets=1.74.0,@aws-cdk/aws-events=1.74.0,@aws-cdk/aws-iam=1.74.0,@aws-cdk/aws-kms=1.74.0,@aws-cdk/aws-lambda=1.74.0,@aws-cdk/aws-logs=1.74.0,@aws-cdk/aws-s3=1.74.0,@aws-cdk/aws-s3-assets=1.74.0,@aws-cdk/aws-sqs=1.74.0,@aws-cdk/aws-ssm=1.74.0,@aws-cdk/cloud-assembly-schema=1.74.0,@aws-cdk/core=1.74.0,@aws-cdk/custom-resources=1.74.0,@aws-cdk/cx-api=1.74.0,@aws-cdk/region-info=1.74.0,jsii-runtime=node.js/v14.9.0
    Metadata:
      "aws:cdk:path": cdk-run-demo-stack/CDKMetadata/Default
